{
 "title": "Ceph - CephFS",
 "description": "Ceph CephFS overview for official Ceph Prometheus plugin.",
 "tags": [
  "ceph",
  "cephfs"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "name",
    "label": "name",
    "query": "label_values(ceph_fs_metadata, name)"
   },
   {
    "name": "mdatapool",
    "label": "metadata pool",
    "query": "label_values(ceph_fs_metadata, metadata_pool)"
   },
   {
    "name": "datapool",
    "label": "data pool",
    "query": "label_values(ceph_fs_metadata, data_pools)"
   }
  ]
 },
 "panels": [
  {
   "title": "Active MDS",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "count(ceph_mds_metadata)" }
   ]
  },
  {
   "title": "MetaData Used",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "ceph_pool_bytes_used{pool_id=\"$mdatapool\"}"
    }
   ]
  },
  {
   "title": "MetaData Read",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 0 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "irate(ceph_pool_rd_bytes{pool_id=\"$mdatapool\"}[$interval])"
    }
   ]
  },
  {
   "title": "Data Used",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "ceph_pool_bytes_used{pool_id=\"$datapool\"}"
    }
   ]
  },
  {
   "title": "Data Write",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 0 },
   "format": "iops",
   "valueName": "current",
   "targets": [
    {
     "expr": "irate(ceph_pool_wr{pool_id=\"$datapool\"}[$interval])"
    }
   ]
  },
  {
   "title": "Client Requests",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(ceph_mds_server_handle_client_request[$interval]))"
    }
   ]
  },
  {
   "title": "Client Sessions",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(ceph_mds_sessions_session_count)"
    }
   ]
  },
  {
   "title": "MDS Inodes",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "sum(ceph_mds_inodes)" }
   ]
  },
  {
   "title": "MetaData Write",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 2 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "irate(ceph_pool_wr_bytes{pool_id=\"$mdatapool\"}[$interval])"
    }
   ]
  },
  {
   "title": "Data Read",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 2 },
   "format": "iops",
   "valueName": "current",
   "targets": [
    {
     "expr": "irate(ceph_pool_rd{pool_id=\"$datapool\"}[$interval])"
    }
   ]
  },
  {
   "title": "MetaData Available",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 4 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "ceph_pool_max_avail{pool_id=\"$mdatapool\"} / (ceph_pool_bytes_used{pool_id=\"$mdatapool\"} + ceph_pool_max_avail{pool_id=\"$mdatapool\"})"
    }
   ]
  },
  {
   "title": "MetaData Read",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 4 },
   "format": "iops",
   "valueName": "current",
   "targets": [
    {
     "expr": "irate(ceph_pool_rd{pool_id=\"$mdatapool\"}[$interval])"
    }
   ]
  },
  {
   "title": "Data Available",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 4 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "ceph_pool_max_avail{pool_id=\"$datapool\"} / (ceph_pool_bytes_used{pool_id=\"$datapool\"} + ceph_pool_max_avail{pool_id=\"$datapool\"})"
    }
   ]
  },
  {
   "title": "Data Write",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 4 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "irate(ceph_pool_wr_bytes{pool_id=\"$datapool\"}[$interval])"
    }
   ]
  },
  {
   "title": "Forward Requests",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 4 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(ceph_mds_forward[$interval]))"
    }
   ]
  },
  {
   "title": "Reply Latency(ms)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 4 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(ceph_mds_reply_latency_sum[$interval])) * 1000 / sum(increase(ceph_mds_reply_latency_count[$interval]))"
    }
   ]
  },
  {
   "title": "MDS Caps",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 4 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "sum(ceph_mds_caps)" }
   ]
  },
  {
   "title": "MetaData Write",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 6 },
   "format": "iops",
   "valueName": "current",
   "targets": [
    {
     "expr": "irate(ceph_pool_wr{pool_id=\"$mdatapool\"}[$interval])"
    }
   ]
  },
  {
   "title": "Data Read",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 6 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "irate(ceph_pool_rd_bytes{pool_id=\"$datapool\"}[$interval])"
    }
   ]
  },
  { "title": "MDS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Clent Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(ceph_mds_server_handle_client_request[$interval])",
     "legendFormat": "{{ ceph_daemon }}"
    }
   ]
  },
  {
   "title": "Forward Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(ceph_mds_forward[$interval])",
     "legendFormat": "{{ ceph_daemon }}"
    }
   ]
  },
  {
   "title": "Slave Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(ceph_mds_server_handle_slave_request[$interval])",
     "legendFormat": "{{ ceph_daemon }}"
    }
   ]
  },
  {
   "title": "Session Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ceph_mds_sessions_session_count",
     "legendFormat": "{{ ceph_daemon }}"
    }
   ]
  },
  {
   "title": "Reply Latency(ms)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(ceph_mds_reply_latency_sum[$interval]) * 1000 / increase(ceph_mds_reply_latency_count[$interval])",
     "legendFormat": "{{ ceph_daemon }}"
    }
   ]
  },
  { "title": "Log", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Log Submit",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(ceph_mds_log_evadd{}[$interval])",
     "legendFormat": "{{ ceph_daemon }}"
    }
   ]
  },
  {
   "title": "Log Events",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "ceph_mds_log_ev", "legendFormat": "{{ ceph_daemon }}" }
   ]
  },
  {
   "title": "Log Segments",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "ceph_mds_log_seg", "legendFormat": "{{ ceph_daemon }}" }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Inodes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "ceph_mds_mem_ino", "legendFormat": "{{ ceph_daemon }}" }
   ]
  },
  {
   "title": "Exported Inodes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "ceph_mds_exported_inodes", "legendFormat": "{{ ceph_daemon }}" }
   ]
  },
  {
   "title": "Imported Inodes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "ceph_mds_imported_inodes", "legendFormat": "{{ ceph_daemon }}" }
   ]
  },
  {
   "title": "Dentries",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "ceph_mds_mem_dn", "legendFormat": "{{ ceph_daemon }}" }
   ]
  },
  {
   "title": "Caps",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "ceph_mds_caps", "legendFormat": "{{ ceph_daemon }}" }
   ]
  },
  { "title": "MetaData Pool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Pool Storage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "ceph_pool_max_avail{pool_id=~\"^$mdatapool$\"}",
     "legendFormat": "Avilable"
    },
    {
     "expr": "ceph_pool_bytes_used{pool_id=~\"^$mdatapool$\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "ceph_pool_bytes_used{pool_id=~\"^$mdatapool$\"} + ceph_pool_max_avail{pool_id=~\"^$mdatapool$\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "ceph_pool_raw_bytes_used{pool_id=~\"^$mdatapool$\"}",
     "legendFormat": "Raw Used"
    }
   ]
  },
  {
   "title": "Objects in Pool",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 14, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ceph_pool_objects{pool_id=~\"$mdatapool\"}",
     "legendFormat": "Objects"
    },
    {
     "expr": "ceph_pool_dirty{pool_id=~\"$mdatapool\"}",
     "legendFormat": "Dirty Objects"
    },
    {
     "expr": "ceph_pool_quota_objects{pool_id=~\"$mdatapool\"}",
     "legendFormat": "Quota Objects"
    }
   ]
  },
  {
   "title": "Usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 47 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "ceph_pool_bytes_used{pool_id=\"$mdatapool\"} / (ceph_pool_bytes_used{pool_id=\"$mdatapool\"} + ceph_pool_max_avail{pool_id=\"$mdatapool\"})"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "none", "label": "IOPS" }
   ],
   "targets": [
    {
     "expr": "irate(ceph_pool_rd{pool_id=~\"$mdatapool\"}[$interval])",
     "legendFormat": "Read"
    },
    {
     "expr": "irate(ceph_pool_wr{pool_id=~\"$mdatapool\"}[$interval])",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "decbytes", "label": "IOPS" }
   ],
   "targets": [
    {
     "expr": "irate(ceph_pool_rd_bytes{pool_id=~\"$mdatapool\"}[$interval])",
     "legendFormat": "Read Bytes"
    },
    {
     "expr": "irate(ceph_pool_wr_bytes{pool_id=~\"$mdatapool\"}[$interval])",
     "legendFormat": "Write Bytes"
    }
   ]
  },
  { "title": "Data Pool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "Pool Storage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "ceph_pool_max_avail{pool_id=~\"^$datapool$\"}",
     "legendFormat": "Avilable"
    },
    {
     "expr": "ceph_pool_bytes_used{pool_id=~\"^$datapool$\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "ceph_pool_bytes_used{pool_id=~\"^$datapool$\"} + ceph_pool_max_avail{pool_id=~\"^$datapool$\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "ceph_pool_raw_bytes_used{pool_id=~\"^$datapool$\"}",
     "legendFormat": "Raw Used"
    }
   ]
  },
  {
   "title": "Objects in Pool",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 14, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ceph_pool_objects{pool_id=~\"$datapool\"}",
     "legendFormat": "Objects"
    },
    {
     "expr": "ceph_pool_dirty{pool_id=~\"$datapool\"}",
     "legendFormat": "Dirty Objects"
    },
    {
     "expr": "ceph_pool_quota_objects{pool_id=~\"$datapool\"}",
     "legendFormat": "Quota Objects"
    }
   ]
  },
  {
   "title": "Usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 62 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "ceph_pool_bytes_used{pool_id=\"$datapool\"} / (ceph_pool_bytes_used{pool_id=\"$datapool\"} + ceph_pool_max_avail{pool_id=\"$datapool\"})"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "none", "label": "IOPS" }
   ],
   "targets": [
    {
     "expr": "irate(ceph_pool_rd{pool_id=~\"$datapool\"}[$interval])",
     "legendFormat": "Read"
    },
    {
     "expr": "irate(ceph_pool_wr{pool_id=~\"$datapool\"}[$interval])",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 69 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "irate(ceph_pool_rd_bytes{pool_id=~\"$datapool\"}[$interval])",
     "legendFormat": "Read Bytes"
    },
    {
     "expr": "irate(ceph_pool_wr_bytes{pool_id=~\"$datapool\"}[$interval])",
     "legendFormat": "Write Bytes"
    }
   ]
  },
  {
   "title": "ceph_mds_cache_num_strays",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "ceph_mds_cache_num_strays" }
   ]
  },
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total[5m])*100"
    }
   ]
  }
 ]
}